server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training
    username: root
    password: 210723

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

razorpay:
  key_id: YOUR_KEY_ID
  key_secret: YOUR_SECRET
