server:
  port: 8003
 
spring:
  application:
    name: MarketingService
    
  datasource:
    url: jdbc:mysql://localhost:3306/crm
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 210723
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com:
      crm: 
        marketing: INFO
  file:
    name: myLogs/app.logging

springdoc:
  api-docs:
    path: /api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
